### ISSUE TITLE
Add ChangeLog, ESLint, editorconf and others from boilerplate

### ISSUE THREAD

**Issue by ai** [admdh/postcss-high-contrast#1]
[Our pluin boilerplate](https://github.com/postcss/postcss-plugin-boilerplate) contains many very useful thing for open source project. You should move them:
- [x] `ChangeLog`
- [x] ESLint
- [x] `.editorconfig`
- [x] `LICENSE`
- [x] `.npmignore`

**Comment by eduarddotgg** [comment]
Done!
