### ISSUE TITLE
Delete unused CSS

### ISSUE THREAD

**Issue by talgautb** [admdh/postcss-high-contrast#12]
What about to delete unused CSS ?
for example:
main.css:

```
body {
  position: relative;
}
```

contast.css:

```
body {
  position: relative;
  background-color: #000;
}
```

did we need `position: relative;` in new CSS ? may be new option for it?)

**Comment by eduarddotgg** [comment]
this can be an option. 

P.S. By the way pull requests are welcomed.)

**Comment by eduarddotgg** [comment]
Done!
