### ISSUE TITLE
Contrast image

### ISSUE THREAD

**Issue by talgautb** [admdh/postcss-high-contrast#9]
you can add some options for images, and to use css filter (grayscale or contrast?) for it

**Comment by eduarddotgg** [comment]
And what about background images? i think it could be better if there was another plugin for that, so this one was not so complicated.

**Comment by talgautb** [comment]
@admdh look [here for example](https://egov.kz/cms/ru)

**Comment by eduarddotgg** [comment]
what do you think about this options:
imageContarst: grayscale/invert/contrast
imageSelectors: [img] - selectors for aggressive mode

**Comment by eduarddotgg** [comment]
done!
